Two fer
GlebKosianchuk/Exercism pull request #2
Opened 2021-08-10 16:33 UTC by GlebKosianchuk

2021-08-10 16:50 UTC, astro6703 requested changes
Though the solution works, it's not ideal. At first consider using ternary operator instead of ordinary `if` and fix some style issues.

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +
Here and below: remove all redundant blank lines.

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +﻿using System;
Redundant using statement. Initially it was used to import `NotImplementedException` from `System` namespace.

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +    public static string Speak(string x=null)
1. Parameter name should be descriptive (such as `string name`)
2. Fix formatting: `string x = null`

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +        if (x != null )
Consider using ternary operator instead of ordinary `if` here.

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +        return ($"One for {x}, one for me.");
1. Fix indentation.
2. Here and in below: redundant parentheses in return statements;

2021-08-10 16:50 UTC, astro6703 commented on csharp/two-fer/TwoFer.cs
> +    // can be called both without any arguments and also by passing one string argument.
Comments are redundant.

2021-08-12 11:04 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +﻿using System;
It still persists

2021-08-12 11:04 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +    // can be called both without any arguments and also by passing one string argument.
Still persists

2021-08-12 11:15 UTC, kgorbenko requested changes

2021-08-12 11:15 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +               return (answer);
1. Indentation within one block should be the same.
2. String is duplicating, you need to to find a way to parameterize it.
3. Parentheses surrounding strings and in return statement are redundant.
4. Always declare variables with assignment: 'var answer = ...'.

2021-08-12 11:15 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +﻿using System;
Redundant using statement. Initially it was used to import `NotImplementedException` from `System` namespace, which is not used here anymore.

2021-08-12 13:15 UTC, kgorbenko requested changes

2021-08-12 13:15 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +        var x = name != null ? $"{name}" : "you";
Consider using null coalescing operator instead of ternary operator.

2021-08-13 07:34 UTC, kgorbenko requested changes
One last thing: try to get a better use of default parameter.

2021-08-13 07:34 UTC, kgorbenko commented on csharp/two-fer/TwoFer.cs
> +    public static string Speak(string name = null)
1. You could get a betted use of default parameter. Think of it.
2. (Optional) Since your solution now is a one-liner, consider using expression body.

2021-08-13 08:32 UTC, kgorbenko approved these changes
Nicely done!

2021-08-13 08:40 UTC, merged